---

- include: "facts.yml"
  tags: "always"

- include: "packages-stretch.yml"
  tags: "redis-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version >= "9"

- include: "redis.yml"
  tags: "redis-redis"

- include: "optimize.yml"
  tags: "redis-optimize"

