---

- name: "reload services"
  when: rbenv_reload is defined
  service:
    name: "{{ item }}"
    state: "reloaded"
  loop: rbenv_reload

- name: "restart services"
  when: rbenv_restart is defined
  service:
    name: "{{ item }}"
    state: "restarted"
  loop: rbenv_restart

