---

- name: upgrade system
  hosts: all
  tasks:
    - apt: update_cache=yes upgrade=dist

- name: "install unbound as a local DNSSEC-validating resolver"
  hosts: "all"
  become: yes
  gather_facts: True
  roles:
    - role: "unbound"
      tags: ["unbound"]


- name: "install postgres for use with discourse"
  hosts: "postgres"
  become: yes
  gather_facts: True

  roles:
    - role: "postgres-discourse"
      tags: ["postgres-discourse"]


- name: "install and configure redis"
  hosts: "redis"
  become: yes
  gather_facts: True

  roles:
    - role: "redis"
      tags: ["redis"]

- name: "install npm"
  hosts: "discourse"
  roles:
    - role: "geerlingguy.nodejs"

- name: "install discourse, unicorn and nginx"
  hosts: "discourse"
  gather_facts: True
  become: yes

  roles:
    - role: "discourse"
      tags: ["discourse"]

    - role: "nginx-discourse"
      tags: ["nginx-discourse"]

    - role: "opendkim"
      tags: ["opendkim"]
      when: discourse_smtp_address == 'localhost' and dkim_enabled

    - role: "postfix"
      tags: ["postfix"]
      when: discourse_smtp_address == 'localhost'


