---

- name: "create /var/www/discourse directory"
  file:
    dest: "/var/www/discourse"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"
    seuser: "staff_u"
    serole: "object_r"
    setype: "httpd_sys_content_t"
    selevel: "s0"

- name: "https://github.com/discourse/discourse.git"
  git:
    repo: "https://github.com/discourse/discourse.git"
    dest: "/var/www/discourse"
    version: "{{ discourse_version }}"
    update: True
    force: True
  become_user: "discourse"
  notify:
    - "reload discourse-unicorn"

- name: "install discourse.conf"
  template:
    src: "discourse.conf.j2"
    dest: "/var/www/discourse/config/discourse.conf"
    owner: "discourse"
    group: "discourse"
    mode: "0644"
  notify:
    - "reload discourse-unicorn"

- name: "create /var/www/discourse/log directory"
  file:
    dest: "/var/www/discourse/log"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"
    seuser: "staff_u"
    serole: "object_r"
    setype: "var_log_t"
    selevel: "s0"

- name: "create /var/www/discourse/log/rails directory"
  file:
    dest: "/var/www/discourse/log/rails"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"
    seuser: "staff_u"
    serole: "object_r"
    setype: "var_log_t"
    selevel: "s0"

- name: "create /var/www/discourse/plugins directory"
  file:
    dest: "/var/www/discourse/plugins"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"

- name: "create /var/www/discourse/public/backups directory"
  file:
    dest: "/var/www/discourse/public/backups"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"

- name: "create /var/www/discourse/tmp directory"
  file:
    dest: "/var/www/discourse/tmp"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"

- name: "create /var/www/discourse/tmp/pids directory"
  file:
    dest: "/var/www/discourse/tmp/pids"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"
    seuser: "staff_u"
    serole: "object_r"
    setype: "var_run_t"
    selevel: "s0"

- name: "create /var/www/discourse/tmp/sockets directory"
  file:
    dest: "/var/www/discourse/tmp/sockets"
    owner: "discourse"
    group: "discourse"
    mode: "0755"
    state: "directory"

- name: "install /etc/logrotate.d/discourse"
  copy:
    src: "discourse.logrotate"
    dest: "/etc/logrotate.d/discourse"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "install plugins"
  when: discourse_plugins is defined
  git:
    repo: "{{ item.repo }}"
    dest: "/var/www/discourse/plugins/{{ item.name }}"
    version: "{{ item.version }}"
    update: True
    force: True
  become_user: "discourse"
  with_items: "{{ discourse_plugins }}"
  notify:
    - "reload discourse-unicorn"

- name: "remove multisite.yml"
  when: discourse_multisite is not defined
  file:
    dest: "/var/www/discourse/config/multisite.yml"
    state: "absent"
  notify:
    - "reload discourse-unicorn"

