---

- name: create /var/www/discourse/public/logos
  file:
    dest: /var/www/discourse/public/logos
    owner: discourse
    group: discourse
    mode: 0755
    state: directory

- name: install debianfr logos
  copy:
    src: "files/{{ item }}"
    dest: "/var/www/discourse/public/logos/{{ item }}"
  with_items:
    - favicon.ico
    - debianfr.org.small.png
    - debianfr.org.petit.png

- name: create /var/www/fonts
  file:
    dest: /var/www/fonts
    owner: discourse
    group: discourse
    mode: 0755
    state: directory

- name: install debianfr fonts
  copy:
    src: "files/fonts/"
    dest: "/var/www/fonts/"

