---

- include: "facts.yml"
  tags: "always"

- include: "user.yml"
  tags: "discourse-user"

- include: "packages-jessie.yml"
  tags: "discourse-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "app.yml"
  tags: "discourse-app"

- include: "bundler.yml"
  tags: "discourse-bundler"

- include: "npm.yml"
  tags: "discourse-npm"

- include: "db.yml"
  tags: "discourse-db"

- include: "multisite.yml"
  tags: "discourse-multisite"
  when: discourse_multisite is defined

- include: "assets.yml"
  tags: "discourse-assets"

- include: debianfr.yml
  tags: discourse-debianfr

- include: "unicorn.yml"
  tags: "discourse-unicorn"

