---

- include: "packages-stretch.yml"
  tags: "postfix-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version >= "9"

- include: "configs.yml"
  tags: "postfix-configs"

- include: "services.yml"
  tags: "postfix-services"

