---

- include: "facts.yml"
  tags: "always"

- include: "packages.yml"
  tags: "opendkim-packages"

- include: "configs.yml"
  tags: "opendkim-configs"

- include: "services.yml"
  tags: "opendkim-services"

