---

- include: "facts.yml"
  tags: "always"

- include: "packages-stretch.yml"
  tags: "opendkim-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version >= "9"

- include: "configs.yml"
  tags: "opendkim-configs"

- include: "services.yml"
  tags: "opendkim-services"

