---

- name: "install /etc/nginx/sites-enabled/discourse.conf"
  template:
    src: "discourse.conf.j2"
    dest: "/etc/nginx/sites-enabled/discourse.conf"
    owner: "root"
    group: "root"
    mode: "0640"
  notify:
    - "nginx upgrade"

- name: "remove /etc/nginx/sites-enabled/default"
  file:
    dest: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - "nginx upgrade"

