---

- include: "facts.yml"
  tags: "always"

- include: "packages.yml"
  tags: "nginx-packages"

- include: "configs.yml"
  tags: "nginx-configs"

- include: "pki.yml"
  tags: "nginx-pki"
  when: tls_enabled

- include: "services.yml"
  tags: "nginx-services"

