---

- include: "facts.yml"
  tags: "always"

- include: "packages-jessie.yml"
  tags: "nginx-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "configs.yml"
  tags: "nginx-configs"

- include: "pki.yml"
  tags: "nginx-pki"
  when: tls_enabled

- include: "services.yml"
  tags: "nginx-services"

