---

- include: "facts.yml"
  tags: "always"

- include: "user.yml"
  tags: "rbenv-user"

- include: "packages-jessie.yml"
  tags: "rbenv-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "ruby.yml"
  tags: "rbenv-ruby"

