---

- name: assert that rbenv_ruby_version is defined
  assert: { that: "rbenv_ruby_version is defined" }

- name: assert that rbenv_user is defined
  assert: { that: "rbenv_user is defined" }

- name: Setup rbenv
  become: yes
  become_user: "{{ rbenv_user }}"
  block:
    - name: https://github.com/rbenv/rbenv
      git:
        repo: "https://github.com/rbenv/rbenv.git"
        dest: "{{ rbenv_home }}/.rbenv"
        version: "{{ rbenv_version }}"
        force: True

    - name: https://github.com/rbenv/ruby-build
      git:
        repo: "https://github.com/rbenv/ruby-build.git"
        dest: "{{ rbenv_home }}/.rbenv/plugins/ruby-build"
        version: "{{ rbenv_ruby_build_version }}"
        force: True

    - name: install ruby with rbenv
      command: >
        /usr/bin/ionice -c 3 /usr/bin/nice -n 19
        {{ rbenv_home }}/.rbenv/bin/rbenv install {{ rbenv_ruby_version }}
      args:
        creates: "{{ rbenv_home }}/.rbenv/versions/{{ rbenv_ruby_version }}"
      environment:
        MAKE_OPT: "{{ rbenv_make_opt }}"
        RBENV_ROOT: "{{ rbenv_home }}/.rbenv/"
      notify:
        - "reload services"
        - "restart services"

    - name: rbenv rehash
      command: "{{ rbenv_home }}/.rbenv/bin/rbenv rehash"
      changed_when: False

- name: set global ruby version
  template:
    src: "ruby-version.j2"
    dest: "{{ rbenv_home }}/.rbenv/version"
    owner: "{{ rbenv_user }}"
    group: "{{ rbenv_user }}"
    mode: "0644"
  notify:
    - "reload services"
    - "restart services"

