---

- include: "facts.yml"
  tags: "always"

- include: "packages-jessie.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "user.yml"
  tags: "postgres-user"

- include: "initdb.yml"
  tags: "postgres-initdb"

- include: "tmpfiles.yml"
  tags: "postgres-tmpfiles"

