---

- include: "facts.yml"
  tags: "always"

- include: "packages.yml"
  tags: "postgres-repo"

- include: "user.yml"
  tags: "postgres-user"

- include: "initdb.yml"
  tags: "postgres-initdb"

- include: "tmpfiles.yml"
  tags: "postgres-tmpfiles"

