---

- name: "create .pgsql_profile"
  command: "/usr/bin/touch {{ postgres_homedir }}/.pgsql_profile"
  args:
    creates: "{{ postgres_homedir }}/.pgsql_profile"
  become_user: "postgres"

- name: "export PATH"
  lineinfile:
    dest: "{{ postgres_homedir }}/.pgsql_profile"
    line: "export PATH"
    insertafter: "EOF"

- name: "set path to postgres binaries"
  when: ansible_os_family == "Debian"
  lineinfile:
    dest: "{{ postgres_homedir }}/.pgsql_profile"
    line: "PATH=/usr/lib/postgresql/{{ postgres_version }}/bin:$PATH"
    insertbefore: "^export PATH$"

